name: SunSpace
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59604
title: SunSpace
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c599d'
    - '#ffd7a4'
    - '#6aace6'
    - '#fcffff'
    - '#c89061'
  brandStrength: 0.4375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
